"use client";

import { Plus, X } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import type { FormEvent } from "react";
import { DataTableShell } from "../components/DataTableShell";
import { EmptyState, ErrorState, LoadingState, UnavailableState } from "../components/AsyncStates";
import { PageHeader } from "../components/PageHeader";
import { Section } from "../components/Section";
import { StatusBadge } from "../components/StatusBadge";
import { useApiResource } from "../hooks/useApiResource";
import { ApiClientError, apiClient } from "../lib/api/client";
import { formatUiDate } from "../lib/presentation";
import type { EditableProjectMetadata, EditableProjectStatus, ProjectPriority } from "../lib/api/types";

const EMPTY_PROJECT: EditableProjectMetadata = {
  name: "",
  description: "",
  status: "active",
  priority: "normal",
  tags: [],
};

function parsedTags(value: string): string[] {
  return value.split(",").map((tag) => tag.trim()).filter(Boolean);
}

export function ProjectsView() {
  const router = useRouter();
  const [offset, setOffset] = useState(0);
  const pageSize = 50;
  const resource = useApiResource(
    `projects:${offset}`,
    () => apiClient.getProjects({ limit: pageSize, offset }),
  );
  const [showCreate, setShowCreate] = useState(false);
  const [draft, setDraft] = useState<EditableProjectMetadata>(EMPTY_PROJECT);
  const [tagDraft, setTagDraft] = useState("");
  const [commandStatus, setCommandStatus] = useState<"idle" | "saving" | "error">("idle");
  const [commandMessage, setCommandMessage] = useState("");
  const dirtyCreate = showCreate && (
    draft.name !== ""
    || draft.description !== ""
    || draft.status !== "active"
    || draft.priority !== "normal"
    || tagDraft !== ""
  );

  useEffect(() => {
    const warn = (event: BeforeUnloadEvent) => {
      if (!dirtyCreate) return;
      event.preventDefault();
    };
    const warnNavigation = (event: globalThis.MouseEvent) => {
      if (
        !dirtyCreate
        || event.defaultPrevented
        || event.button !== 0
        || event.metaKey
        || event.ctrlKey
        || event.shiftKey
        || event.altKey
      ) return;
      const anchor = event.target instanceof Element
        ? event.target.closest("a[href]")
        : null;
      if (anchor && !window.confirm("Leave Projects and discard this unsaved Project draft?")) {
        event.preventDefault();
        event.stopPropagation();
      }
    };
    window.addEventListener("beforeunload", warn);
    document.addEventListener("click", warnNavigation, true);
    return () => {
      window.removeEventListener("beforeunload", warn);
      document.removeEventListener("click", warnNavigation, true);
    };
  }, [dirtyCreate]);

  async function createProject(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setCommandStatus("saving");
    setCommandMessage("");
    try {
      const response = await apiClient.createProject({ ...draft, tags: parsedTags(tagDraft) });
      router.push(`/projects/${encodeURIComponent(response.project.project_id)}`);
    } catch (error) {
      const message = error instanceof ApiClientError
        ? error.message
        : "The Project could not be created. Your draft is preserved.";
      setCommandStatus("error");
      setCommandMessage(`${message} Your draft is preserved.`);
    }
  }

  function closeCreate() {
    if (dirtyCreate && !window.confirm("Discard this unsaved Project draft?")) return;
    setShowCreate(false);
    setDraft(EMPTY_PROJECT);
    setTagDraft("");
    setCommandStatus("idle");
    setCommandMessage("");
  }

  return (
    <div className="page-stack">
      <PageHeader
        title="Projects"
        description="Organize related papers and note blocks."
        actions={(
          <button className="reader-control" type="button" onClick={() => setShowCreate(true)} disabled={showCreate}>
            <Plus size={15} />Create Project
          </button>
        )}
      />
      {showCreate ? (
        <Section title="Create Project" description="Nothing is written until you choose Create. Project IDs and timestamps are generated by the service.">
          <form className="project-command-panel" onSubmit={createProject}>
            <div className="project-form-grid">
              <label className="reader-field">
                <span>Name</span>
                <input
                  required
                  maxLength={200}
                  value={draft.name}
                  onChange={(event) => setDraft((current) => ({ ...current, name: event.target.value }))}
                />
              </label>
              <label className="reader-field">
                <span>Description</span>
                <textarea
                  rows={4}
                  maxLength={5000}
                  value={draft.description}
                  onChange={(event) => setDraft((current) => ({ ...current, description: event.target.value }))}
                />
              </label>
              <label className="reader-field">
                <span>Status</span>
                <select
                  value={draft.status}
                  onChange={(event) => setDraft((current) => ({ ...current, status: event.target.value as EditableProjectStatus }))}
                >
                  <option value="active">Active</option>
                  <option value="paused">Paused</option>
                  <option value="done">Done</option>
                </select>
              </label>
              <label className="reader-field">
                <span>Priority</span>
                <select
                  value={draft.priority}
                  onChange={(event) => setDraft((current) => ({ ...current, priority: event.target.value as ProjectPriority }))}
                >
                  <option value="low">Low</option>
                  <option value="normal">Normal</option>
                  <option value="high">High</option>
                </select>
              </label>
              <label className="reader-field project-form-wide">
                <span>Tags (comma separated)</span>
                <input
                  maxLength={2524}
                  value={tagDraft}
                  onChange={(event) => setTagDraft(event.target.value)}
                />
              </label>
            </div>
            <p className="reader-editor__status" role="status">
              {commandStatus === "saving" ? "Creating Project…" : commandMessage}
            </p>
            <div className="reader-editor__actions">
              <button className="reader-control" type="submit" disabled={commandStatus === "saving"}>
                Create Project
              </button>
              <button className="reader-control reader-control--secondary" type="button" onClick={closeCreate} disabled={commandStatus === "saving"}>
                <X size={15} />Cancel
              </button>
            </div>
          </form>
        </Section>
      ) : null}
      {resource.status === "loading" ? <LoadingState label="Loading Projects" /> : null}
      {resource.status === "unavailable" ? <UnavailableState description={resource.message} onRetry={resource.retry} /> : null}
      {resource.status === "error" ? <ErrorState title="Project read model unavailable" description={resource.message} onRetry={resource.retry} /> : null}
      {resource.status === "not-found" ? <ErrorState description={resource.message} onRetry={resource.retry} /> : null}
      {resource.status === "success" ? (
        <Section title="Projects" description={`${resource.data.total} Project${resource.data.total === 1 ? "" : "s"}.`}>
          {resource.data.items.length === 0 ? (
            <EmptyState title="No Projects" description="The local Project store is empty. This view never substitutes sample Projects." />
          ) : (
            <>
              <DataTableShell label="Stored Projects">
                <table>
                <thead><tr><th>Project</th><th>Status</th><th>Priority</th><th>Tags</th><th>Paper links</th><th>Note Block links</th><th>Updated</th></tr></thead>
                <tbody>
                  {resource.data.items.map((project) => (
                    <tr key={project.project_id}>
                      <td>
                        <Link className="paper-link" href={`/projects/${encodeURIComponent(project.project_id)}`}>{project.name}</Link>
                      </td>
                      <td><StatusBadge tone={project.status === "active" ? "accent" : "neutral"}>{project.status}</StatusBadge></td>
                      <td>{project.priority}</td>
                      <td>
                        <div className="tag-list">
                          {project.tags.length
                            ? project.tags.map((tag) => <StatusBadge key={tag}>{tag}</StatusBadge>)
                            : <span className="muted-text">None stored</span>}
                        </div>
                      </td>
                      <td>{project.linked_paper_count}</td>
                      <td>{project.linked_note_block_count}</td>
                      <td>{formatUiDate(project.updated_at)}</td>
                    </tr>
                  ))}
                </tbody>
                </table>
              </DataTableShell>
              <div className="reader-editor__actions" aria-label="Project pages">
                <button className="reader-control reader-control--secondary" type="button" disabled={resource.data.offset === 0} onClick={() => setOffset(Math.max(0, resource.data.offset - pageSize))}>Previous</button>
                <span className="muted-text">Showing {resource.data.offset + 1}–{resource.data.offset + resource.data.items.length} of {resource.data.total}</span>
                <button className="reader-control reader-control--secondary" type="button" disabled={!resource.data.has_more} onClick={() => setOffset(resource.data.offset + resource.data.items.length)}>Next</button>
              </div>
            </>
          )}
        </Section>
      ) : null}
    </div>
  );
}
